---
- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - software-properties-common

# Now that we have the apt-add-repository tool (from software-properties-common)
- name: Add brightbox ruby repo to apt
  become: true
  shell: apt-add-repository -y ppa:brightbox/ruby-ng

# Sync-up the new repo
- name: Update apt cache
  apt:
    update_cache: yes

- name: install ruby-switch
  become: true
  shell: apt-get -y install ruby2.3 ruby-switch

- name: switch to ruby 2.3
  shell: ruby-switch --set ruby2.3

- name: Install Packages | bundler
  gem:
    state: latest
    name: bundler
    user_install: no

- name: Install Packages | gem
  gem:
    state: latest
    name: "{{ item }}"
    user_install: no
  with_items: ruby_gems
  when: ruby_gems is iterable
